name       : rttr
version    : 0.9.6
release    : 2
source     :
    - https://www.rttr.org/releases/rttr-0.9.6-src.tar.gz : f62caee43016489320f8a69145c9208cddd72e451ea95618bc26a49a4cd6c990
license    : MIT
component  : programming.library
summary    : C++ Reflection Library
description: |
    C++ Reflection Library
setup      : |
    %patch -p1 < $pkgfiles/fix-include-permissions.patch
    %cmake_ninja \
        -DBUILD_STATIC=TRUE \
        -DBUILD_WITH_STATIC_RUNTIME_LIBS=TRUE \
        -DBUILD_EXAMPLES=OFF \
        -DBUILD_UNIT_TESTS=OFF \
        -DBUILD_PACKAGE=OFF \
        -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
